Repository dang-der/dangder-client, pull requests merged in 2022-11, with the labels that each got.

#21 :camera_flash: 매칭 후기
  pages/review/[dogId]/index.tsx
  pages/review/write/index.tsx
  src/Commons/Store/Review/Review.ts
  src/Commons/Types/Generated/types.ts
  src/Components/Commons/layout/index.tsx
  src/Components/Commons/layout/logo_header/index.tsx
  src/Components/Commons/layout/page_header/index.tsx
  src/Components/Units/Auth/Login/Login.container.tsx
  src/Components/Units/Auth/Redirect/Redirect.container.tsx
  src/Components/Units/Chat/ChatRoom/ChatRoom.container.tsx
  src/Components/Units/Chat/ChatRoom/ChatRoom.presenter.tsx
  src/Components/Units/Chat/ChatRoom/ChatRoom.styles.ts
  src/Components/Units/Detail/DogDetail.container.tsx
  src/Components/Units/Detail/DogDetail.presenter.tsx
  src/Components/Units/Detail/DogDetail.styles.tsx
  src/Components/Units/Profile/DogProfilePage.presenter.tsx
  src/Components/Units/Review/Item/ReviewItem.style.ts
  src/Components/Units/Review/Item/ReviewItem.tsx
  src/Components/Units/Review/List/ReceivedReviewList.container.tsx
  src/Components/Units/Review/List/ReceivedReviewList.style.ts
  src/Components/Units/Review/Review.queries.ts
  src/Components/Units/Review/Write/ReviewWrite.container.tsx
  src/Components/Units/Review/Write/ReviewWrite.presenter.tsx
  src/Components/Units/Review/Write/ReviewWrite.style.ts
Labels: 🧩 Feature

#23 :camera_flash: 관심사 그룹 채팅
  pages/chat/[roomId]/index.tsx
  pages/interests/chat/[roomId]/index.tsx
  src/Commons/Store/Chat/Chat.ts
  src/Components/Commons/layout/index.tsx
  src/Components/Commons/layout/page_header/index.tsx
  src/Components/Units/Auth/Redirect/Redirect.container.tsx
  src/Components/Units/Chat/Chat.queries.tsx
  src/Components/Units/Chat/ChatRoom/ChatRoom.container.tsx
  src/Components/Units/Chat/ChatRoom/ChatRoom.presenter.tsx
  src/Components/Units/Profile/Init/InitProfile.container.tsx
Labels: 🧩 Feature

#28 :camera_flash: 유저 신고하기
  public/report_btn.png
  src/Components/Units/Detail/DogDetail.presenter.tsx
  src/Components/Units/Detail/DogDetail.queries.ts
  src/Components/Units/Detail/DogDetail.styles.tsx
Labels: 🧩 Feature

#31 :camera_flash: 댕더패스 구매 모달 리팩터링
  src/Components/Units/Detail/DogDetail.container.tsx
  src/Components/Units/Main/Card.tsx
  src/Components/Units/Main/DogMain.container.tsx
  src/Components/Units/Main/DogMain.presenter.tsx
  src/Components/Units/PassModal/BuyPassTicketModal.tsx
  src/Components/Units/PassModal/Payment.queries.ts
  src/Components/Units/Profile/DogProfilePage.container.tsx
  src/Components/Units/Profile/DogProfilePage.presenter.tsx
  src/Components/Units/Profile/PassTicketModal/PassTicketModal.tsx
  src/Components/Units/TodayDog/TodayDogList.container.tsx
Labels: ⚙️ Refector

#36 :camera_flash: 어드민 페이지 로그인/회원가입 feature-#14
  pages/_app.tsx
  pages/admin/index.tsx
  pages/admin/signup/index.tsx
  pages/admin/user/index.tsx
  src/Commons/Library/getAdminAccessToken.tsx
  src/Commons/Store/Admin/AccessToken.ts
  src/Commons/Store/Admin/AdminInfoState.ts
  src/Commons/Store/Admin/SignUpState.ts
  src/Components/Commons/layout/admin_navigation/index.tsx
  src/Components/Commons/layout/index.tsx
  src/Components/Units/Admin/Auth/Login/AdminLogin.container.tsx
  src/Components/Units/Admin/Auth/Login/AdminLogin.presenter.tsx
  src/Components/Units/Admin/Auth/Login/AdminLogin.quries.ts
  src/Components/Units/Admin/Auth/Login/AdminLogin.styles.ts
  src/Components/Units/Admin/Auth/SignUp/AdminSignUp.container.tsx
  src/Components/Units/Admin/Auth/SignUp/AdminSignUp.presenter.tsx
  src/Components/Units/Admin/Auth/SignUp/AdminSignUp.quries.ts
  src/Components/Units/Admin/Auth/SignUp/AdminSignUp.styles.ts
  src/Components/Units/Admin/User/AdminUser.container.tsx
  styles/AdminGlobalStyles.ts
  tsconfig.json
Labels: ⚙️ Refector, 🧩 Feature

#40 :camera_flash: 어드민 페이지 내역 api 연결 및 검색 기능
  pages/_app.tsx
  pages/admin/blocks/index.tsx
  pages/admin/dogs/index.tsx
  pages/admin/payments/index.tsx
  pages/admin/reports/index.tsx
  pages/admin/user/index.tsx
  pages/admin/users/index.tsx
  src/Commons/Types/Generated/types.ts
  src/Components/Commons/layout/admin_navigation/index.tsx
  src/Components/Commons/layout/index.tsx
  src/Components/Units/Admin/Auth/Login/AdminLogin.presenter.tsx
  src/Components/Units/Admin/Auth/Login/AdminLogin.styles.ts
  src/Components/Units/Admin/Auth/SignUp/AdminSignUp.styles.ts
  src/Components/Units/Admin/Blocks/AdminBlocks.container.tsx
  src/Components/Units/Admin/Blocks/AdminBlocks.presenter.tsx
  src/Components/Units/Admin/Blocks/AdminBlocks.queries.ts
  src/Components/Units/Admin/Blocks/AdminBlocks.styles.ts
  src/Components/Units/Admin/Dogs/AdminDogs.container.tsx
  src/Components/Units/Admin/Dogs/AdminDogs.presenter.tsx
  src/Components/Units/Admin/Dogs/AdminDogs.queries.ts
  src/Components/Units/Admin/Dogs/AdminDogs.styles.ts
  src/Components/Units/Admin/Payments/AdminPayments.container.tsx
  src/Components/Units/Admin/Payments/AdminPayments.presenter.tsx
  src/Components/Units/Admin/Payments/AdminPayments.queries.ts
  src/Components/Units/Admin/Payments/AdminPayments.styles.ts
  src/Components/Units/Admin/Reports/AdminReports.container.tsx
  src/Components/Units/Admin/Reports/AdminReports.presenter.tsx
  src/Components/Units/Admin/Reports/AdminReports.queries.ts
  src/Components/Units/Admin/Reports/AdminReports.styles.ts
  src/Components/Units/Admin/User/AdminUser.container.tsx
  src/Components/Units/Admin/Users/AdminUsers.container.tsx
  src/Components/Units/Admin/Users/AdminUsers.presenter.tsx
  src/Components/Units/Admin/Users/AdminUsers.queries.ts
  src/Components/Units/Admin/Users/AdminUsers.styles.ts
  styles/AdminGlobalStyles.ts
Labels: 🧩 Feature
